///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexWordpressLibrary.Record.Verify
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyCompare2Value recording.
    /// </summary>
    [TestModule("c96a2ee8-0702-4e51-a795-22b9b5ff3ef9", ModuleType.Recording, 1)]
    public partial class VerifyCompare2Value : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RanorexWordpressLibrary.RanorexWordpressLibraryRepository repository.
        /// </summary>
        public static global::RanorexWordpressLibrary.RanorexWordpressLibraryRepository repo = global::RanorexWordpressLibrary.RanorexWordpressLibraryRepository.Instance;

        static VerifyCompare2Value instance = new VerifyCompare2Value();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyCompare2Value()
        {
            varString1 = "";
            varString2 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyCompare2Value Instance
        {
            get { return instance; }
        }

#region Variables

        string _varString1;

        /// <summary>
        /// Gets or sets the value of variable varString1.
        /// </summary>
        [TestVariable("c450e95d-e41f-4b3f-8692-e331d2d85d65")]
        public string varString1
        {
            get { return _varString1; }
            set { _varString1 = value; }
        }

        string _varString2;

        /// <summary>
        /// Gets or sets the value of variable varString2.
        /// </summary>
        [TestVariable("0043180c-e6f1-4887-a0fd-4a0c932256e9")]
        public string varString2
        {
            get { return _varString2; }
            set { _varString2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Ranorex.AutomationHelpers.UserCodeCollections.ValidationLibrary.CompareValues(varString1, varString2);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
