///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexWordpressLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RanorexWordpressLibraryRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("78cdb3e0-f1ee-4349-aaba-d9e99da4313e")]
    public partial class RanorexWordpressLibraryRepository : RepoGenBaseFolder
    {
        static RanorexWordpressLibraryRepository instance = new RanorexWordpressLibraryRepository();
        RanorexWordpressLibraryRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the RanorexWordpressLibraryRepository element repository.
        /// </summary>
        [RepositoryFolder("78cdb3e0-f1ee-4349-aaba-d9e99da4313e")]
        public static RanorexWordpressLibraryRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RanorexWordpressLibraryRepository() 
            : base("RanorexWordpressLibraryRepository", "/", null, 0, false, "78cdb3e0-f1ee-4349-aaba-d9e99da4313e", ".\\RepositoryImages\\RanorexWordpressLibraryRepository78cdb3e0.rximgres")
        {
            _applicationundertest = new RanorexWordpressLibraryRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("78cdb3e0-f1ee-4349-aaba-d9e99da4313e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("8ca35afe-5cc1-48cc-9960-5dfc3a45bd5e")]
        public virtual RanorexWordpressLibraryRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RanorexWordpressLibraryRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("8ca35afe-5cc1-48cc-9960-5dfc3a45bd5e")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RanorexWordpressLibraryRepositoryFolders.LeftSideBarFolder _leftsidebar;
            RanorexWordpressLibraryRepositoryFolders.PostFolder _post;
            RepoItemInfo _userloginInfo;
            RepoItemInfo _userpassInfo;
            RepoItemInfo _wpsubmitInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='webtest.ranorex.org']", parentFolder, 30000, null, false, "8ca35afe-5cc1-48cc-9960-5dfc3a45bd5e", "")
            {
                _leftsidebar = new RanorexWordpressLibraryRepositoryFolders.LeftSideBarFolder(this);
                _post = new RanorexWordpressLibraryRepositoryFolders.PostFolder(this);
                _userloginInfo = new RepoItemInfo(this, "UserLogin", ".//input[#'user_login']", ".//input[#'user_login']", 30000, null, "d2415b1d-8434-4232-b0b4-5e9ab2986712");
                _userpassInfo = new RepoItemInfo(this, "UserPass", ".//input[#'user_pass']", ".//input[#'user_pass']", 30000, null, "231b4d45-693d-44f4-9a60-c3413eb1effd");
                _wpsubmitInfo = new RepoItemInfo(this, "WpSubmit", ".//input[#'wp-submit']", ".//input[#'wp-submit']", 30000, null, "2490cfb5-276b-4de9-9000-a704831ca085");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8ca35afe-5cc1-48cc-9960-5dfc3a45bd5e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8ca35afe-5cc1-48cc-9960-5dfc3a45bd5e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserLogin item.
            /// </summary>
            [RepositoryItem("d2415b1d-8434-4232-b0b4-5e9ab2986712")]
            public virtual Ranorex.InputTag UserLogin
            {
                get
                {
                    return _userloginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserLogin item info.
            /// </summary>
            [RepositoryItemInfo("d2415b1d-8434-4232-b0b4-5e9ab2986712")]
            public virtual RepoItemInfo UserLoginInfo
            {
                get
                {
                    return _userloginInfo;
                }
            }

            /// <summary>
            /// The UserPass item.
            /// </summary>
            [RepositoryItem("231b4d45-693d-44f4-9a60-c3413eb1effd")]
            public virtual Ranorex.InputTag UserPass
            {
                get
                {
                    return _userpassInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPass item info.
            /// </summary>
            [RepositoryItemInfo("231b4d45-693d-44f4-9a60-c3413eb1effd")]
            public virtual RepoItemInfo UserPassInfo
            {
                get
                {
                    return _userpassInfo;
                }
            }

            /// <summary>
            /// The WpSubmit item.
            /// </summary>
            [RepositoryItem("2490cfb5-276b-4de9-9000-a704831ca085")]
            public virtual Ranorex.InputTag WpSubmit
            {
                get
                {
                    return _wpsubmitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The WpSubmit item info.
            /// </summary>
            [RepositoryItemInfo("2490cfb5-276b-4de9-9000-a704831ca085")]
            public virtual RepoItemInfo WpSubmitInfo
            {
                get
                {
                    return _wpsubmitInfo;
                }
            }

            /// <summary>
            /// The LeftSideBar folder.
            /// </summary>
            [RepositoryFolder("5d447b3f-3e38-41b5-b117-cb19f82e1703")]
            public virtual RanorexWordpressLibraryRepositoryFolders.LeftSideBarFolder LeftSideBar
            {
                get { return _leftsidebar; }
            }

            /// <summary>
            /// The Post folder.
            /// </summary>
            [RepositoryFolder("c72343c8-af1a-46aa-b739-23d896fd328c")]
            public virtual RanorexWordpressLibraryRepositoryFolders.PostFolder Post
            {
                get { return _post; }
            }
        }

        /// <summary>
        /// The LeftSideBarFolder folder.
        /// </summary>
        [RepositoryFolder("5d447b3f-3e38-41b5-b117-cb19f82e1703")]
        public partial class LeftSideBarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _postsInfo;
            RepoItemInfo _contextmenuaddnewInfo;

            /// <summary>
            /// Creates a new LeftSideBar  folder.
            /// </summary>
            public LeftSideBarFolder(RepoGenBaseFolder parentFolder) :
                    base("LeftSideBar", "", parentFolder, 30000, null, false, "5d447b3f-3e38-41b5-b117-cb19f82e1703", "")
            {
                _postsInfo = new RepoItemInfo(this, "Posts", ".//li[#'menu-posts']//div[@innertext='Posts']", ".//li[#'menu-posts']/?/?/div[@innertext='Posts']", 30000, null, "755005be-9dec-4c99-9e90-134ace2f8ee0");
                _contextmenuaddnewInfo = new RepoItemInfo(this, "contextmenuAddNew", ".//li[#'menu-posts']//li[@class='wp-first-item current']/..//a[@innertext='Add New']", ".//li[#'menu-posts']//a[@innertext='Add New']", 30000, null, "fa819b3f-baff-42d9-a1c4-b5f68a6bb379");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5d447b3f-3e38-41b5-b117-cb19f82e1703")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5d447b3f-3e38-41b5-b117-cb19f82e1703")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Posts item.
            /// </summary>
            [RepositoryItem("755005be-9dec-4c99-9e90-134ace2f8ee0")]
            public virtual Ranorex.DivTag Posts
            {
                get
                {
                    return _postsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Posts item info.
            /// </summary>
            [RepositoryItemInfo("755005be-9dec-4c99-9e90-134ace2f8ee0")]
            public virtual RepoItemInfo PostsInfo
            {
                get
                {
                    return _postsInfo;
                }
            }

            /// <summary>
            /// The contextmenuAddNew item.
            /// </summary>
            [RepositoryItem("fa819b3f-baff-42d9-a1c4-b5f68a6bb379")]
            public virtual Ranorex.ATag contextmenuAddNew
            {
                get
                {
                    return _contextmenuaddnewInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The contextmenuAddNew item info.
            /// </summary>
            [RepositoryItemInfo("fa819b3f-baff-42d9-a1c4-b5f68a6bb379")]
            public virtual RepoItemInfo contextmenuAddNewInfo
            {
                get
                {
                    return _contextmenuaddnewInfo;
                }
            }
        }

        /// <summary>
        /// The PostFolder folder.
        /// </summary>
        [RepositoryFolder("c72343c8-af1a-46aa-b739-23d896fd328c")]
        public partial class PostFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titleaddnewpostInfo;
            RepoItemInfo _txttitleInfo;
            RepoItemInfo _txtcontentInfo;
            RepoItemInfo _btnpublishInfo;

            /// <summary>
            /// Creates a new Post  folder.
            /// </summary>
            public PostFolder(RepoGenBaseFolder parentFolder) :
                    base("Post", "", parentFolder, 30000, null, false, "c72343c8-af1a-46aa-b739-23d896fd328c", "")
            {
                _titleaddnewpostInfo = new RepoItemInfo(this, "titleAddNewPost", ".//div[#'wpbody-content']//h2[@innertext='Add New Post']", ".//div[#'wpbody-content']/?/?/h2[@innertext='Add New Post']", 30000, null, "4965f802-de8b-42b0-b38a-073c4da64aab");
                _txttitleInfo = new RepoItemInfo(this, "txtTitle", ".//input[#'title']", ".//input[#'title']", 30000, null, "a6e53366-8522-4528-9cb5-c22e731fec0c");
                _txtcontentInfo = new RepoItemInfo(this, "txtContent", ".//textarea[#'content']", ".//textarea[#'content']", 30000, null, "68aa9aa8-f921-4dad-906c-c52e8131441c");
                _btnpublishInfo = new RepoItemInfo(this, "btnPublish", ".//input[#'publish']", ".//input[#'publish']", 30000, null, "461d1826-e1c9-41e2-b2bc-6af888f26c21");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c72343c8-af1a-46aa-b739-23d896fd328c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c72343c8-af1a-46aa-b739-23d896fd328c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The titleAddNewPost item.
            /// </summary>
            [RepositoryItem("4965f802-de8b-42b0-b38a-073c4da64aab")]
            public virtual Ranorex.H2Tag titleAddNewPost
            {
                get
                {
                    return _titleaddnewpostInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The titleAddNewPost item info.
            /// </summary>
            [RepositoryItemInfo("4965f802-de8b-42b0-b38a-073c4da64aab")]
            public virtual RepoItemInfo titleAddNewPostInfo
            {
                get
                {
                    return _titleaddnewpostInfo;
                }
            }

            /// <summary>
            /// The txtTitle item.
            /// </summary>
            [RepositoryItem("a6e53366-8522-4528-9cb5-c22e731fec0c")]
            public virtual Ranorex.InputTag txtTitle
            {
                get
                {
                    return _txttitleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtTitle item info.
            /// </summary>
            [RepositoryItemInfo("a6e53366-8522-4528-9cb5-c22e731fec0c")]
            public virtual RepoItemInfo txtTitleInfo
            {
                get
                {
                    return _txttitleInfo;
                }
            }

            /// <summary>
            /// The txtContent item.
            /// </summary>
            [RepositoryItem("68aa9aa8-f921-4dad-906c-c52e8131441c")]
            public virtual Ranorex.TextAreaTag txtContent
            {
                get
                {
                    return _txtcontentInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The txtContent item info.
            /// </summary>
            [RepositoryItemInfo("68aa9aa8-f921-4dad-906c-c52e8131441c")]
            public virtual RepoItemInfo txtContentInfo
            {
                get
                {
                    return _txtcontentInfo;
                }
            }

            /// <summary>
            /// The btnPublish item.
            /// </summary>
            [RepositoryItem("461d1826-e1c9-41e2-b2bc-6af888f26c21")]
            public virtual Ranorex.InputTag btnPublish
            {
                get
                {
                    return _btnpublishInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The btnPublish item info.
            /// </summary>
            [RepositoryItemInfo("461d1826-e1c9-41e2-b2bc-6af888f26c21")]
            public virtual RepoItemInfo btnPublishInfo
            {
                get
                {
                    return _btnpublishInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
