///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexWordpressLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RanorexWordpressLibraryRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("78cdb3e0-f1ee-4349-aaba-d9e99da4313e")]
    public partial class RanorexWordpressLibraryRepository : RepoGenBaseFolder
    {
        static RanorexWordpressLibraryRepository instance = new RanorexWordpressLibraryRepository();
        RanorexWordpressLibraryRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the RanorexWordpressLibraryRepository element repository.
        /// </summary>
        [RepositoryFolder("78cdb3e0-f1ee-4349-aaba-d9e99da4313e")]
        public static RanorexWordpressLibraryRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RanorexWordpressLibraryRepository() 
            : base("RanorexWordpressLibraryRepository", "/", null, 0, false, "78cdb3e0-f1ee-4349-aaba-d9e99da4313e", ".\\RepositoryImages\\RanorexWordpressLibraryRepository78cdb3e0.rximgres")
        {
            _applicationundertest = new RanorexWordpressLibraryRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("78cdb3e0-f1ee-4349-aaba-d9e99da4313e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("8ca35afe-5cc1-48cc-9960-5dfc3a45bd5e")]
        public virtual RanorexWordpressLibraryRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RanorexWordpressLibraryRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("8ca35afe-5cc1-48cc-9960-5dfc3a45bd5e")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _userloginInfo;
            RepoItemInfo _userpassInfo;
            RepoItemInfo _wpsubmitInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='webtest.ranorex.org']", parentFolder, 30000, null, false, "8ca35afe-5cc1-48cc-9960-5dfc3a45bd5e", "")
            {
                _userloginInfo = new RepoItemInfo(this, "UserLogin", ".//input[#'user_login']", ".//input[#'user_login']", 30000, null, "d2415b1d-8434-4232-b0b4-5e9ab2986712");
                _userpassInfo = new RepoItemInfo(this, "UserPass", ".//input[#'user_pass']", ".//input[#'user_pass']", 30000, null, "231b4d45-693d-44f4-9a60-c3413eb1effd");
                _wpsubmitInfo = new RepoItemInfo(this, "WpSubmit", ".//input[#'wp-submit']", ".//input[#'wp-submit']", 30000, null, "2490cfb5-276b-4de9-9000-a704831ca085");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8ca35afe-5cc1-48cc-9960-5dfc3a45bd5e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8ca35afe-5cc1-48cc-9960-5dfc3a45bd5e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserLogin item.
            /// </summary>
            [RepositoryItem("d2415b1d-8434-4232-b0b4-5e9ab2986712")]
            public virtual Ranorex.InputTag UserLogin
            {
                get
                {
                    return _userloginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserLogin item info.
            /// </summary>
            [RepositoryItemInfo("d2415b1d-8434-4232-b0b4-5e9ab2986712")]
            public virtual RepoItemInfo UserLoginInfo
            {
                get
                {
                    return _userloginInfo;
                }
            }

            /// <summary>
            /// The UserPass item.
            /// </summary>
            [RepositoryItem("231b4d45-693d-44f4-9a60-c3413eb1effd")]
            public virtual Ranorex.InputTag UserPass
            {
                get
                {
                    return _userpassInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPass item info.
            /// </summary>
            [RepositoryItemInfo("231b4d45-693d-44f4-9a60-c3413eb1effd")]
            public virtual RepoItemInfo UserPassInfo
            {
                get
                {
                    return _userpassInfo;
                }
            }

            /// <summary>
            /// The WpSubmit item.
            /// </summary>
            [RepositoryItem("2490cfb5-276b-4de9-9000-a704831ca085")]
            public virtual Ranorex.InputTag WpSubmit
            {
                get
                {
                    return _wpsubmitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The WpSubmit item info.
            /// </summary>
            [RepositoryItemInfo("2490cfb5-276b-4de9-9000-a704831ca085")]
            public virtual RepoItemInfo WpSubmitInfo
            {
                get
                {
                    return _wpsubmitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
