///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sample
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SampleRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("92b579ec-2c85-4811-9a12-f6f3c4b315f9")]
    public partial class SampleRepository : RepoGenBaseFolder
    {
        static SampleRepository instance = new SampleRepository();

        /// <summary>
        /// Gets the singleton class instance representing the SampleRepository element repository.
        /// </summary>
        [RepositoryFolder("92b579ec-2c85-4811-9a12-f6f3c4b315f9")]
        public static SampleRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SampleRepository() 
            : base("SampleRepository", "/", null, 0, false, "92b579ec-2c85-4811-9a12-f6f3c4b315f9", ".\\RepositoryImages\\SampleRepository92b579ec.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("92b579ec-2c85-4811-9a12-f6f3c4b315f9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SampleRepositoryFolders
    {
    }
#pragma warning restore 0436
}
