///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexWordpressLibrary.Record
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DragAndVerify2 recording.
    /// </summary>
    [TestModule("bcfe8d6e-a694-4d75-8d53-cf26768aa43e", ModuleType.Recording, 1)]
    public partial class DragAndVerify2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RanorexWordpressLibrary.RanorexWordpressLibraryRepository repository.
        /// </summary>
        public static global::RanorexWordpressLibrary.RanorexWordpressLibraryRepository repo = global::RanorexWordpressLibrary.RanorexWordpressLibraryRepository.Instance;

        static DragAndVerify2 instance = new DragAndVerify2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DragAndVerify2()
        {
            varTextLink = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DragAndVerify2 Instance
        {
            get { return instance; }
        }

#region Variables

        string _varTextLink;

        /// <summary>
        /// Gets or sets the value of variable varTextLink.
        /// </summary>
        [TestVariable("671106a6-fdd7-4caa-b97f-6fdd31c8b8bb")]
        public string varTextLink
        {
            get { return _varTextLink; }
            set { _varTextLink = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Ranorex.AutomationHelpers.UserCodeCollections.DragNDropLibrary.DragAndDrop(repo.ApplicationUnderTest.Post.InsertMediaButton, repo.ApplicationUnderTest.Post.txtContent);
            Delay.Milliseconds(0);
            
            Common.CommonCode.Verify_Text_Exist(repo.ApplicationUnderTest.Post.QtContentCloseInfo, "value", varTextLink);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
