///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexWordpressLibrary.Record
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyPost recording.
    /// </summary>
    [TestModule("f39d4368-a401-4aa8-aa09-0e034d735468", ModuleType.Recording, 1)]
    public partial class VerifyPost : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RanorexWordpressLibrary.RanorexWordpressLibraryRepository repository.
        /// </summary>
        public static global::RanorexWordpressLibrary.RanorexWordpressLibraryRepository repo = global::RanorexWordpressLibrary.RanorexWordpressLibraryRepository.Instance;

        static VerifyPost instance = new VerifyPost();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyPost()
        {
            title = "";
            content = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyPost Instance
        {
            get { return instance; }
        }

#region Variables

        string _title;

        /// <summary>
        /// Gets or sets the value of variable title.
        /// </summary>
        [TestVariable("efe8c176-ace1-49f0-9ad7-48f88194b300")]
        public string title
        {
            get { return _title; }
            set { _title = value; }
        }

        string _content;

        /// <summary>
        /// Gets or sets the value of variable content.
        /// </summary>
        [TestVariable("f23cb5d0-fdb5-454e-853b-26dcfed2e2d1")]
        public string content
        {
            get { return _content; }
            set { _content = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Common.CommonCode.Verify_Text_Exist(repo.ApplicationUnderTest.SinglePost.lblPagetitleInfo, "InnerText", title);
            Delay.Milliseconds(0);
            
            Common.CommonCode.Verify_Text_Exist(repo.ApplicationUnderTest.SinglePost.lblContentInfo, "InnerText", content);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
